---
- hosts: webservers
  connection: docker
  vars:
    db_name: wordpress
    db_user: wordpress
    db_password: wordpress
    db_host: wordpress_mysql
  tasks:
    - name: ensure php7.3 is installed
      apt:
        name: 
          - php7.3
          - php7.3-mysql
          # - php7.3-cli
          - php7.3-json
          - php7.3-pdo
          - php7.3-zip 
          - php7.3-gd 
          # - php7.3-mbstring
          # - php7.3-curl
          - php7.3-xml
          # - php7.3-bcmath
        state: present
        update_cache: yes
        force_apt_get: yes
    - name: uncompress wordpress.tar.gz
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        remote_src: yes
        dest: /var/www/html
        validate_certs: no
        owner: www-data
        group: www-data
    - name: disable default website
      shell: a2dissite 000-default.conf
    - name: copy wordpress vhost configuration
      copy:
        src: templates/apache2/wordpress.conf
        dest: /etc/apache2/sites-available/wordpress.conf
    - name: enable wordpress vhost
      shell: a2ensite wordpress.conf
    - name: restart apache2 service
      service:
        name: apache2
        state: restarted
    - name: copy wordpress vhost configuration
      template:
        src: templates/wordpress/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
      